# Generated by Django 4.2.21 on 2025-06-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_user_groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user_groups",
                    models.ManyToManyField(
                        related_name="group_collections",
                        to="openedx_user_groups.usergroup",
                    ),
                ),
            ],
        ),
    ]
