# Generated by Django 4.2.21 on 2025-06-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_user_groups", "0002_groupcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="scope",
            name="reference_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
