# Generated by Django 4.2.21 on 2025-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_user_groups", "0003_scope_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scope",
            name="object_id",
            field=models.CharField(max_length=255),
        ),
    ]
