# Generated by Django 4.2.21 on 2025-06-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_user_groups", "0004_alter_scope_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scope",
            name="reference_id",
        ),
    ]
